name: Update Stack Table


on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Запуск раз в день
  workflow_dispatch:

jobs:
  update-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Tech Stack
        uses: arturssmirnovs/tech-stack-readme@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .stack.yml
